Repository Medicare-Call/Medicare-Call-Android, pull requests merged in 2025-09, with the labels that each got.

#107 Docs: 이슈, PR 템플릿 작성 및 CI 문서 작성
  .github/ISSUE_TEMPLATE/chore-task.yml
  .github/ISSUE_TEMPLATE/docs-task.yml
  .github/ISSUE_TEMPLATE/feature-task.yml
  .github/ISSUE_TEMPLATE/fix-task.yml
  .github/ISSUE_TEMPLATE/refactor-task.yml
  .github/PULL_REQUEST_TEAMPLATE.md
  .github/workflows/android-ci.yml
Labels: docs

#118 [Refactor] DI 모듈 재설정 #108
  app/src/main/java/com/konkuk/medicarecall/data/AppModule.kt
  app/src/main/java/com/konkuk/medicarecall/data/di/ApiModule.kt
  app/src/main/java/com/konkuk/medicarecall/data/di/NetworkModule.kt
  app/src/main/java/com/konkuk/medicarecall/data/di/RepositoryModule.kt
  app/src/main/java/com/konkuk/medicarecall/data/repository/DataStoreRepository.kt
  app/src/main/java/com/konkuk/medicarecall/data/repository/ElderIdRepository.kt
  app/src/main/java/com/konkuk/medicarecall/data/repository/ElderRegisterRepository.kt
  app/src/main/java/com/konkuk/medicarecall/data/repository/EldersHealthInfoRepository.kt
  app/src/main/java/com/konkuk/medicarecall/data/repository/EldersInfoRepository.kt
  app/src/main/java/com/konkuk/medicarecall/data/repository/MemberRegisterRepository.kt
  app/src/main/java/com/konkuk/medicarecall/data/repository/NaverPayRepository.kt
  app/src/main/java/com/konkuk/medicarecall/data/repository/NoticeRepository.kt
  app/src/main/java/com/konkuk/medicarecall/data/repository/SetCallRepository.kt
  app/src/main/java/com/konkuk/medicarecall/data/repository/SubscribeRepository.kt
  app/src/main/java/com/konkuk/medicarecall/data/repository/UpdateElderInfoRepository.kt
  app/src/main/java/com/konkuk/medicarecall/data/repository/UserRepository.kt
  app/src/main/java/com/konkuk/medicarecall/data/repository/VerificationRepository.kt
  app/src/main/java/com/konkuk/medicarecall/data/repositoryimpl/DataStoreRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/data/repositoryimpl/ElderIdRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/data/repositoryimpl/ElderRegisterRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/data/repositoryimpl/EldersHealthInfoRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/data/repositoryimpl/EldersInfoRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/data/repositoryimpl/MemberRegisterRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/data/repositoryimpl/NaverPayRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/data/repositoryimpl/NoticeRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/data/repositoryimpl/SetCallRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/data/repositoryimpl/SubscribeRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/data/repositoryimpl/UpdateElderInfoRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/data/repositoryimpl/UserRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/data/repositoryimpl/VerificationRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/domain/usecase/CheckLoginStatusUseCase.kt
  app/src/main/java/com/konkuk/medicarecall/ui/home/data/HomeRepository.kt
  app/src/main/java/com/konkuk/medicarecall/ui/home/data/HomeRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/ui/home/data/HomeService.kt
  app/src/main/java/com/konkuk/medicarecall/ui/home/di/HomeNetworkModule.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/glucoselevel/data/GlucoseRepository.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/glucoselevel/data/GlucoseRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/glucoselevel/data/GlucoseService.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/glucoselevel/di/GlucoseNetworkModule.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/meal/data/MealRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/meal/data/MealService.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/meal/di/MealNetworkModule.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/medicine/data/MedicineRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/medicine/data/MedicineService.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/medicine/di/MedicineNetworkModule.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/sleep/data/SleepRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/sleep/data/SleepService.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/sleep/di/SleepNetworkModule.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/statehealth/data/HealthRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/statehealth/data/HealthService.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/statehealth/di/HealthNetworkModule.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/statemental/data/MentalRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/statemental/data/MentalService.kt
  app/src/main/java/com/konkuk/medicarecall/ui/homedetail/statemental/di/MentalNetworkModule.kt
  app/src/main/java/com/konkuk/medicarecall/ui/statistics/data/StatisticsRepository.kt
  app/src/main/java/com/konkuk/medicarecall/ui/statistics/data/StatisticsRepositoryImpl.kt
  app/src/main/java/com/konkuk/medicarecall/ui/statistics/data/StatisticsService.kt
  app/src/main/java/com/konkuk/medicarecall/ui/statistics/di/StatisticsNetworkModule.kt
  gradlew
Labels: refactor

#128 [Design] 디자인시스템 color 값 수정 #126
  app/src/main/java/com/konkuk/medicarecall/ui/theme/Color.kt
Labels: P2
